apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: o43m78vva-python 
  janus-idp.io/tekton: o43m78vva-python
  backstage.io/kubernetes-id: o43m78vva-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o43m78vva-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml